on:
  - push

jobs:
  build:
    uses: cloud-cli/workflows/.github/workflows/docker-ghcr-build.yml@main
    with:
      name: cloudy-apps/webcontainer-playground
      baseImage: cloud-cli/node:latest
      defaultBranch: main
      withSha: false
      withTag: true
      type: node